63267878: Implementation of Supertrend for C trader
GeorgeFreelanceDeveloper/trend-follow.io pull request #11
Opened 2024-06-02 13:20 UTC by LucyFreelanceDeveloper

2024-06-02 17:12 UTC, GeorgeFreelanceDeveloper requested changes

2024-06-02 17:12 UTC, GeorgeFreelanceDeveloper commented on strategies/trend-follow/SuperTrendFollow/scripts/SuperTrendFollowStrategy.cs
> +            _supertrend = Indicators.Supertrend(AtrPeriod, Factor);
Preved na lokalni promennou.

2024-06-02 17:12 UTC, GeorgeFreelanceDeveloper commented on strategies/trend-follow/SuperTrendFollow/scripts/SuperTrendFollowStrategy.cs
> +             string label = $"SuperTrendFolow_cBot-{Symbol.Name}";
Pridat bool promennou isUptrend = !Double.IsNaN(_supertrend.UpTrend.Last());

2024-06-02 17:12 UTC, GeorgeFreelanceDeveloper commented on strategies/trend-follow/SuperTrendFollow/scripts/SuperTrendFollowStrategy.cs
> +        private bool IsUptrend()
Metodu zrusit.

2024-06-03 18:04 UTC, LucyFreelanceDeveloper commented on strategies/trend-follow/SuperTrendFollow/scripts/SuperTrendFollowStrategy.cs
> +             string label = $"SuperTrendFolow_cBot-{Symbol.Name}";
Done

2024-06-09 11:39 UTC, GeorgeFreelanceDeveloper requested changes

2024-06-09 11:39 UTC, GeorgeFreelanceDeveloper commented on strategies/trend-follow/SuperTrendFollow/scripts/SuperTrendFollowStrategy.cs
> +            bool isSupertrend = !Double.IsNaN(supertrend.UpTrend.Last());
Prejmenoval bych promennou, vystiznejsi nazev je isUpTrend.

2024-06-09 12:47 UTC, LucyFreelanceDeveloper commented on strategies/trend-follow/SuperTrendFollow/scripts/SuperTrendFollowStrategy.cs
> +            bool isSupertrend = !Double.IsNaN(supertrend.UpTrend.Last());
Done

2024-06-09 12:52 UTC, merged